#!/bin/bash

# This script is used to run marvin-cli from source during development.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
deno run --allow-env --allow-net --location "https://cli.amazingmarvin.com" --allow-read --allow-write $DIR/src/index.ts "$@"
